#!/usr/bin/env python
# -*- coding: utf-8 -*-

EXC_CODE = {
    'SERVER_UNKNOWN_ERROR': (100, u'系统未知错误'),
    'DATABASE_UNKNOWN_ERROR': (200, u'数据库未知错误'),
    'NO_PERMISSION': (403, u'没有权限！'),
    'NO_OPER_PERMISSION': (403, u'您没有此操作的权限，请联系管理员，谢谢'),
    'LOGIN_REQUIRED': (401, u'请重新登录，谢谢！'),
    'ID_ERROR': (501, u'输入的ID无效'),
    'ID_NOT_EXIST': (501, u'输入的ID不存在，或该商户（加盟商）暂无数据'),
    'ACCESS_PERMISSION': (501, u'您无权限浏览该商户（加盟商）数据，谢谢！'),
    'ORDER_NOT_EXIST': (501, u'您所查询的订单不存在，请确认重新输入！'),
    'NO_TEAM_DATA_PERMISSION': (501, u'您无权限浏览该数据，谢谢！'),
    'TEAM_ACCESS_PERMISSION': (501, u'您无访问此加盟商数据的权限，请输入您可以访问的加盟商ID，谢谢！'),
    'DATE_DELTA_TOO_LONG': (501, u'您输入的日期超过{}天，请重新输入，谢谢！'),
    'INVALID_INPUT': (501, u'非法输入'),
    'ID_INVALID': (501, u'输入ID({})无效'),
    'PARA_ERROR': (503, u'参数错误.'),
    'ID_NOT_EXIST_FOR_DOWNLOAD': (503, u'输入的ID不存在，或该商户（加盟商）暂无数据'),
    'INVALID_PAY_OBJ_ID': (501, u'打款对象ID不合法'),
    'CUSTOM_BAD_REQUEST': (400, u'{message}'),
    'INPUT_PARA_MUST_EXIST': (501, u'请输入{}'),
    'OP_OBJECT_NUM_LIMIT': (501, u'上传文件包含记录条数超过{},请重新上传'),
    'OBJ_EMPTY_ERROR': (501, u'操作对象为空'),
    'MOBILE_ERROR': (501, u'输入的手机号不合法,请重新输入!'),
    'START_END_DATE_EXIST': (501, u'开始结束日期必须都存在'),
    'START_DATE_INVALID': (501, u'开始日期不合法'),
    'END_DATE_INVALID': (501, u'结束日期不合法'),
    'START_DATE_GREATER_END_DATE': (501, u'开始日期大于结束日期'),
    'USER_OPER_FAIL': (501, u'{}'),
    'ATTACHMENT_NOT_FOUND': (422, u'附件不存在'),
    'CUSTOM_BAD_PARAM': (422, u'{message}'),
}
